name: auth_c
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.10
  custom_info_window: ^1.0.1
  firebase_auth: ^4.18.0
  firebase_core: ^2.27.2
  firebase_dynamic_links: ^5.4.19
  firebase_storage: ^11.6.11
  firebase_ui_auth: ^1.13.1
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.0
  image_picker: ^1.0.7
  location: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
