// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZK3turxz1iFdUJSvlu8SDYDWPyYx1Pp0',
    appId: '1:792254026180:web:1e05b98132f8f94b331491',
    messagingSenderId: '792254026180',
    projectId: 'authc-bb127',
    authDomain: 'authc-bb127.firebaseapp.com',
    storageBucket: 'authc-bb127.appspot.com',
    measurementId: 'G-C32ZF77PYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2QkTwgmjnm7-PKgjf1hvdi7ElylQA4m0',
    appId: '1:792254026180:android:ebcfd720a582b8be331491',
    messagingSenderId: '792254026180',
    projectId: 'authc-bb127',
    storageBucket: 'authc-bb127.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgJHqnSvevMZklUaoKzG5T4DpRSnidzSU',
    appId: '1:792254026180:ios:93262f857f291b80331491',
    messagingSenderId: '792254026180',
    projectId: 'authc-bb127',
    storageBucket: 'authc-bb127.appspot.com',
    iosBundleId: 'com.example.authc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgJHqnSvevMZklUaoKzG5T4DpRSnidzSU',
    appId: '1:792254026180:ios:5263754e354a3aa2331491',
    messagingSenderId: '792254026180',
    projectId: 'authc-bb127',
    storageBucket: 'authc-bb127.appspot.com',
    iosBundleId: 'com.example.authc.RunnerTests',
  );
}
